paths:
  /users/{userId}/missions-chanllenge:
    get:
      tags:
        - Users
      summary: 사용자가 진행중인 미션 목록 조회
      parameters:
        - name: userId
          in: path
          schema:
            type: integer
          required: true
        - name: missionId
          in: query
          required: false
          schema:
            properties:
              missionId:
                type: integer
        - name: paging
          in: query
          required: true
          schema:
            properties:
              size:
                type: integer
      responses:
        '200':
          description: 미션 조회 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                  "missionData": [
                    {
                      "store_name": "가게이름",
                      "mission_body": "미션내용",
				              "term": "D-9",
				              "reward": "500P",
				              "complete": "진행중"
                    },
                    {
                      "store_name": "가게이름",
                      "mission_body": "미션내용",
                      "term": "D-9",
                      "reward": "450P",
                      "complete": "진행중"
                    }
                  ],
                  "cursorId": 3
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.