paths:
  /stores/missions:
    patch:
      tags:
        - Stores
      summary: 미션 도전하기
      parameters:
      - name: patchMission
        in: body
        required: true
        schema:
          properties:
            id:
              type: integer
              description: 미션 아이디
              example: 1
            complete:
              type: string
              description: 미션을 도전 중인 미션으로 만듬
              example: 진행중
      responses:
        '200':
          description: 도전중인 미션이 되었습니다!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "storeName": "임진각",
                  "mission_body": "12000원 이상의 식사를 하세요!",
                  "mission_term": "D-7",
                  "mission_reward": 300,
                  "mission_complete": "진행중"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.