paths:
  /stores/add:
    post:
      tags:
        - Stores
      summary: 특정 지역에 가게 추가 
      parameters:
      - name: addStore
        in: body
        required: true
        schema:
          properties:
            region_id:
              type: integer
              description: 지역 아이디
              example: 1
            name:
              type: string
              description: 가게 이름
              example: 임진각
            address:
              type: string
              description: 가게 주소
              example: 134-11
            check_status:
              type: string
              description: 영업 여부
              example: 영업 중
      responses:
        '200':
          description: 회원 가입 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "region": "공릉동",
                  "storeName": "임진각",
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.